### ISSUE TITLE
multiple unnamed DGNodes in DGXML Output

### ISSUE THREAD

**Issue by 0robustus1** [spechub/Hets#1503]
When processing this ontology: http://staging.ontohub.org/test-um/Chapter8V2 the DGXML contains multiple DGNodes with an empty name attribute.

``` xml
<DGNode name="" reference="false" logic="CASL" refname="?" relxpath="/">
    <Symbols>
      <Symbol kind="sort" name="Nat" iri="Nat" range="/usr/local/opt/hets-lib/UserManual/Chapter3.casl:167.15-167.17">sort Nat</Symbol>
      <Symbol kind="op" name="0" iri="0" range="/usr/local/opt/hets-lib/UserManual/Chapter3.casl:167.23">op 0 : Nat</Symbol>
      <Symbol kind="pred" name="__&lt;__" iri="__&lt;__" range="/usr/local/opt/hets-lib/UserManual/Chapter3.casl:185.12-185.16">pred __&lt;__ : Nat * Nat</Symbol>
      <Symbol kind="op" name="suc" iri="suc" range="/usr/local/opt/hets-lib/UserManual/Chapter3.casl:167.27-167.29">op suc : Nat -&gt; Nat</Symbol>
    </Symbols>
  </DGNode>
  <DGNode name="" reference="false" logic="CASL" refname="?" relxpath="/">
    <Symbols>
      <Symbol kind="sort" name="C
```

This is a problem for ontohub, as ontohub uses the DGNode name-attribute to determine the name of the ontology. It is also inherently expected for the name to be unique inside of one DGraph.
(This is related to ontohub/ontohub#1351)

**Comment by cmaeder** [comment]
@Mihai Probably the node names are not properly set by the architectural static analysis.

**Comment by tillmo** [comment]
probably fixed now?

**Comment by mcodescu** [comment]
The file is missing now, but with https://ontohub.org/casl/hets-lib/UserManual/Chapter8.casl I still get a lot of 
`<DGNode name="" reference="false" logic="CASL" refname="?" relxpath="/" />`.

Nodes with empty names are also

`<DGNode name="" range="/home/mcodescu/repos/testSpecs/Chapter8.casl:190.13-190.50" reference="false" logic="CASL" refname="?" relxpath="/" />`

 introduced by 

`{Cont [Elem] and Generated_Set [Elem]}` 

and 

`<DGNode name="" range="/home/mcodescu/repos/testSpecs/Chapter8.casl:138.21-138.22" reference="false" logic="CASL" refname="?" relxpath="/">`
introduced by 
`{ op diff : Cont[Elem] * Cont[Elem] -> Cont[Elem]
		         forall e:Elem; C, C':Cont[Elem]
		         . e is_in diff(C, C') <=> e is_in C /\ not e is_in C' }`

We need a convention on how to name these nodes.

**Comment by mcodescu** [comment]
Sorry, used an older version of Hets. Indeed, the problem is now solved.

**Comment by mcodescu** [comment]
The xml output of Chapter8.casl is below, and you can see there are no nodes with empty node names.
[Chapter8.txt](https://github.com/spechub/Hets/files/1937365/Chapter8.txt)
