### ISSUE TITLE
error after branching from master

### ISSUE THREAD

**Issue by mcodescu** [spechub/Hets#1637]
I have created a new branch after updating my master branch, then modified Static/DevGraph.hs by adding `| NetworkEntry GDiagram` as a new alternative of GlobalEntry, and wanted to compile. I get: 
```
$ make
DERIVEPATH=; export DERIVEPATH; utils/DrIFT ATC/DevGraph.der.hs > ATC/DevGraph.hs
/bin/sh: 1: cannot create ATC/DevGraph.hs: Permission denied
make: *** [ATC/DevGraph.hs] Error 2
```

**Comment by mcodescu** [comment]
`make clean` does not work either:

```
$ make clean
/bin/sh: 1: ksh: not found
make: *** [clean_pretty] Error 127
```

**Comment by jelmd** [comment]
'apt-get install ksh' should fix it. To find all packages required for building you may also use
`dpkg-checkbuilddeps debian/control 2>&1 | cut -f3- -d":"'`.

**Comment by mcodescu** [comment]
I have installed ksh. Now I can `make clean` without getting an error (but nothing seems to happen), and I still get the same error when trying to make.

**Comment by jelmd** [comment]
Probably artifacts from old builds. Try `make distclean`.

**Comment by mcodescu** [comment]
Thank you, it worked. Should `make clean` and `make distclean` not print a message informing about what is going on? I recall this is the way I found out that some java files needed for OWL were deleted by make clean.

**Comment by jelmd** [comment]
:) . It does just a `rm -rf` and thus is silent a priori. Usually no one wanna see this clutter, but if needed, using the "dry" option '-n' should work, e.g. `make -n distclean`.
