### ISSUE TITLE
build Jammy Ubuntu packages

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2064]
first wait for #2063

**Comment by jelmd** [comment]
Building uni-* packages for jammy via launchpad is not possible right now, because a debian post build check fails. It looks like a ghc-pkg bug: it seems to be not able to parse the packageIDs it creates.

E.g. https://launchpadlibrarian.net/610756706/buildlog_ubuntu-jammy-amd64.libghc-hexpat-dev-src_0.20.13-8.22.4_BUILDING.txt.gz - search for `ghc-pkg: cannot parse`.

**Comment by jelmd** [comment]
The additional dependencies required to build hets are available via https://pkg.cs.ovgu.de/LNF/linux/ubuntu/22.04/ .

Options:
- download the related *.deb package(s) and install using "dpkg -i $file.deb"
- `printf 'deb [trusted=true] http://pkg.cs.ovgu.de/LNF/linux/ubuntu 22.04/\n' | sudo tee /etc/apt/sources.list.d/csmd.list` and `apt-get update`, `apt-get install ...`

I've uploaded the hets source package to https://launchpad.net/~hets/+archive/ubuntu/hets/+packages?field.name_filter=&field.status_filter=published&field.series_filter=jammy , but unless https://bugs.launchpad.net/bugs/1986483                                         
 has not been fixed, required packages as well as hets are not available via launchpad.(I hope it gets fixed soon and does not rise a "who-blames-who" religious war, which usually takes a long time to get resolved, if at all).

However, unfortunately it doesn't build even with local build packages available via https://pkg.cs.ovgu.de/ packages. @daniilsvc can you have a look at it?

I'm on vacation for the next 3 weeks, but let me know, if you think things have been fixed and worth for a next try (sometimes weather is bad or I'm simply bored ;-) )...

**Comment by daniilsvc** [comment]
Unfortunately I still can't install package on my Ubuntu Jammy VM.
```
sudo apt-get install libghc-list-dev libghc-hexpat-dev libghc-aterm-dev libghc-uni-util-dev libghc-uni-events-dev libghc-uni-posixutil-dev libghc-uni-reactor-dev libghc-uni-htk-dev
```

produces error:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libghc-aterm-dev : Depends: ghc (< 8.8.2) but 8.8.4-3 is to be installed
 libghc-hexpat-dev : Depends: ghc (< 8.8.2) but 8.8.4-3 is to be installed
 libghc-list-dev : Depends: ghc (< 8.8.2) but 8.8.4-3 is to be installed
 libghc-uni-events-dev : Depends: ghc (< 8.8.2) but 8.8.4-3 is to be installed
 libghc-uni-htk-dev : Depends: ghc (< 8.8.2) but 8.8.4-3 is to be installed
 libghc-uni-posixutil-dev : Depends: ghc (< 8.8.2) but 8.8.4-3 is to be installed
 libghc-uni-reactor-dev : Depends: ghc (< 8.8.2) but 8.8.4-3 is to be installed
 libghc-uni-util-dev : Depends: ghc (< 8.8.2) but 8.8.4-3 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by daniilsvc** [comment]
There ist no `pkg.cs.ovgu.de` in `/etc/apt/sources.list`. Only in `/etc/apt/srouces.list.d/csmd.list`.
```
cat /etc/apt/sources.list
#deb cdrom:[Ubuntu 22.04 LTS _Jammy Jellyfish_ - Release amd64 (20220419)]/ jammy main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://de.archive.ubuntu.com/ubuntu/ jammy main restricted
# deb-src http://de.archive.ubuntu.com/ubuntu/ jammy main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://de.archive.ubuntu.com/ubuntu/ jammy-updates main restricted
# deb-src http://de.archive.ubuntu.com/ubuntu/ jammy-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://de.archive.ubuntu.com/ubuntu/ jammy universe
# deb-src http://de.archive.ubuntu.com/ubuntu/ jammy universe
deb http://de.archive.ubuntu.com/ubuntu/ jammy-updates universe
# deb-src http://de.archive.ubuntu.com/ubuntu/ jammy-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://de.archive.ubuntu.com/ubuntu/ jammy multiverse
# deb-src http://de.archive.ubuntu.com/ubuntu/ jammy multiverse
deb http://de.archive.ubuntu.com/ubuntu/ jammy-updates multiverse
# deb-src http://de.archive.ubuntu.com/ubuntu/ jammy-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://de.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
# deb-src http://de.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu jammy-security main restricted
# deb-src http://security.ubuntu.com/ubuntu jammy-security main restricted
deb http://security.ubuntu.com/ubuntu jammy-security universe
# deb-src http://security.ubuntu.com/ubuntu jammy-security universe
deb http://security.ubuntu.com/ubuntu jammy-security multiverse
# deb-src http://security.ubuntu.com/ubuntu jammy-security multiverse

# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching "deb cdrom"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.
```

```
cat /etc/apt/sources.list.d/csmd.list
deb [trusted=true] http://pkg.cs.ovgu.de/LNF/linux/ubuntu 20.04/
```

Of course if I comment out source in `/etc/apt/sources.list.d/csmd.list` I got `E: Unable to locate package ...`.

`apt-cache policy libghc-aterm-dev` gives next:
```
libghc-aterm-dev:
  Installed: (none)
  Candidate: 0.1.0.2-2
  Version table:
     0.1.0.2-2 500
        500 http://pkg.cs.ovgu.de/LNF/linux/ubuntu 20.04/ Packages
```
I run `apt-get update` but still can't install packages. Error is the same as above.

**Comment by jelmd** [comment]
> There ist no `pkg.cs.ovgu.de` in `/etc/apt/sources.list`. Only in `/etc/apt/srouces.list.d/csmd.list`.

OK. That's good.

> ```
> cat /etc/apt/sources.list
...
That's ok, too.

> ```
> cat /etc/apt/sources.list.d/csmd.list
> deb [trusted=true] http://pkg.cs.ovgu.de/LNF/linux/ubuntu 20.04/
> ```

Ahh, here we go: You need to adjust the sub directory to the related `lsb_release -rs` (20.04 == focal). So replace 20.04 with 22.04 and it should work.

> Of course if I comment out source in `/etc/apt/sources.list.d/csmd.list` I got `E: Unable to locate package ...`.

OK, so no launchpad in the way :)

> `apt-cache policy libghc-aterm-dev` gives next:
> 
> ```
> libghc-aterm-dev:
>   Installed: (none)
>   Candidate: 0.1.0.2-2
>   Version table:
>      0.1.0.2-2 500
>         500 http://pkg.cs.ovgu.de/LNF/linux/ubuntu 20.04/ Packages
> ```
> 
> I run `apt-get update` but still can't install packages. Error is the same as above.

Yes, because focal packages would not work on jammy - one would need to tell ghc at least, where to look them up. I don't know the compiler internals to say, whether this would be sufficient, but I guess, they put the binaries in versioned directories for reason.

**Comment by daniilsvc** [comment]
What an error...
Then everything is fine. I've installed packages and compiled Hets without stack successfully.

**Comment by jelmd** [comment]
Uhmm, did you ran `make distclean` before? If in doubts running a `make distclean` is always a good idea.

My stderr.out is attached as [fail.txt](https://github.com/spechub/Hets/files/9389356/fail.txt)

**Comment by daniilsvc** [comment]
I assume you compile it on `master`. I test it at branch [make_hets_compitable_with_ghc_8.8.4](https://github.com/spechub/Hets/tree/make_hets_compitable_with_ghc_8.8.4), corresponding PR #2067. The purpose of that branch is exactly to eliminate these errors.

**Comment by jelmd** [comment]
Yepp, public packages are build from master per default. So please let me know, when the PR got merged or the master got fixed otherwise.

**Comment by daniilsvc** [comment]
PR #2067 was successfully merged. You can test packages for Jammy on `master` branch.

**Comment by jelmd** [comment]
fails now on focal as well as jammy with:
```
utils/DtdToHaskell-src/DtdToHaskell.hs:23:1: error:
    Could not find module `DtdToHaskell.TypeDef'
    Use -v to see a list of the files searched for.
   |
23 | import DtdToHaskell.TypeDef (ppTypeDef, mangle)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

utils/DtdToHaskell-src/DtdToHaskell.hs:24:1: error:
    Could not find module `DtdToHaskell.Convert'
    Use -v to see a list of the files searched for.
   |
24 | import DtdToHaskell.Convert (dtd2TypeDef)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

utils/DtdToHaskell-src/DtdToHaskell.hs:25:1: error:
    Could not find module `DtdToHaskell.Instance'
    Use -v to see a list of the files searched for.
   |
25 | import DtdToHaskell.Instance (mkInstance)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
make[1]: *** [Makefile:602: utils/DtdToHaskell] Error 1
make: *** [Makefile:946: hets.bin] Error 2
```

**Comment by daniilsvc** [comment]
Can't reproduce it. I've just successfully compiled hets on my focal with command `STACK= make hets`.  The command that compiles  hets is next:
`ghc -optl-s -XTemplateHaskell -threaded -rtsopts -j  --make    -DNOHTTP  -DUNIX -DUNI_PACKAGE -DHASKELINE     -DWARP1   -DHAXML_COMPAT -DRDFLOGIC -DCASLEXTENSIONS   -Wall -fwarn-tabs -fwarn-unrecognised-pragmas -fno-warn-orphans -fno-warn-unused-do-bind   -o hets hets.hs`

I guess, in `Makefile` line 598 (where target is `$(DTD2HS)`) is responsible for this error. But with flag `--make` ghc should be able to find modules like `DtdToHaskell.TypeDef` automatically as they reflect dir structure (`DtdToHaskell/TypeDef.hs`). 

`ghc --version`
`The Glorious Glasgow Haskell Compilation System, version 8.6.5`

**Comment by daniilsvc** [comment]
After `rm utils/DtdToHaskell` I run `STACK= make utils/DtdToHaskell` and it compiles without mistakes. So I'm confused how could I reproduce the error.

**Comment by jelmd** [comment]
Check out a fresh copy of the master branch and try to compile it.

**Comment by daniilsvc** [comment]
1) `make distclean`
2) `make install-owl-tools` (when I clean project I need it to build new `OWL2/OWL2Parser.jar`)
3) `STACK= make hest 1>compileOutput_865_nostack.txt 2>compileErr_865_nostack.txt`

And Hets compiled successfully. Files `compileOutput_865_nostack.txt` and `compileErr_865_nostack.txt` attached.
[compileOutput_865_nostack.txt](https://github.com/spechub/Hets/files/9503722/compileOutput_865_nostack.txt)
[compileErr_865_nostack.txt](https://github.com/spechub/Hets/files/9503723/compileErr_865_nostack.txt)

**Comment by daniilsvc** [comment]
I have to say that I had a compilation error in file `utils/DrIFT-src/ParseLib2.hs`. Line 48 (`import Control.Monad.Fail`) was commented but actually should not. But that is the only problem that I faced so far, still can't reproduce your error.

**Comment by jelmd** [comment]
Hmmm, you really checked out a new copy? Please do:

```
cd /var/tmp
git clone https://github.com/spechub/Hets hets
cd hets
make distclean
STACK= make
```

> 1. `make distclean`

To make sure run a `git diff` after it. You should see the problem. If not, run `make -n distclean` and show the output.

>     2. `make install-owl-tools` (when I clean project I need it to build new `OWL2/OWL2Parser.jar`)

Can you show/explain in detail, why it is needed to build the hets binary? If i is needed now, it needs to be reflected in the Makefile.

>     3. `STACK= make hets 1>compileOutput_865_nostack.txt 2>compileErr_865_nostack.txt`
>
> And Hets compiled successfully. Files `compileOutput_865_nostack.txt` and `compileErr_865_nostack.txt` attached.

It shouldn't compile. If it does, we need to find out why. First would be to check your environment (run `env` and attach the output).

**Comment by daniilsvc** [comment]
OK, I got the error. If I run `STACK= make utils/DtdToHaskell` after `make distclean` - then I reproduce it. The reason is line 678 in Makefile - it removes sources for DtdToHaskell but we need them. The trick is that target `utils/DtdToHaskell` is triggered only when we need target `Isabelle/IsaExport.hs`. This works only in cases described in line 109 in Makefile, which is not the case for me...

Gonna be fixed soon

**Comment by jelmd** [comment]
OK. Actually the root cause is an incomplete Makefile change in commit 0f41693916b5471d7395e5473860d766503b1182 - attaching the fix, so you can add it to the other changes.
[14_makefile.patch.txt](https://github.com/spechub/Hets/files/9508053/14_makefile.patch.txt)

**Comment by daniilsvc** [comment]
Problem should be fixed in `master` now.

**Comment by jelmd** [comment]
Thanx! Unfortunately ompilation of the master still fails for focal as well as jammy (NeSyPatterns/AS.der.hs is an empty file). BTW: Is it possible to fix  utils/DtdToHaskell-src/DtdToHaskell/*.hs wrt. the warnings as well?
[jammy-errors.txt](https://github.com/spechub/Hets/files/9580119/jammy-errors.txt)

**Comment by jelmd** [comment]
Actually found the problem: The comment in NeSyPatterns/AS.der.hs line 19 col 23 contains an UTF-8 character (\ue28093 .. en dash). It should be replaced by a hyphen-minus (\x2d) alias normal dash.

Check: `rm NeSyPatterns/AS.hs; LC_CTYPE=C make hets`

Finding the problem: `iconv -f UTF-8 -t ISO8859-1 NeSyPatterns/AS.der.hs`
If there is an character, which cannot be converted to ASCII, it stops at and reports the related position.

**Comment by jelmd** [comment]
Hopefully the last thing to fix is Persistence/MySQL.hs (works for focal but not for jammy):
[sql-error.txt](https://github.com/spechub/Hets/files/9581360/sql-error.txt)

**Comment by daniilsvc** [comment]
@jelmd, before I reproduce your error with sql, another one fired on Jammy in my case:
```
Common/SetColimit.hs:37:1: error:
    Could not find module 'Data.Relation'
    Perhaps you meant Data.Ratio (from base-4.13.0.0)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
37 | import qualified Data.Relation as Rel
```

The problem here that package `relation` is not installed. If we look here #2047 - no package of kind `libghc-relation-dev` is mentioned. Do we forget to mention this package as requirements for Hets installation?

**Comment by jelmd** [comment]
Yes, it seems it has been added after v0.106.0 without adding the dependencies to the debian/control file, too. So you need to install it manually e.g. using apt-get.

**Comment by tillmo** [comment]
@jelmd then now you should be able to build jammy packages, right? (after adding `libghc-relation-dev` to the debian/control file)

**Comment by jelmd** [comment]
Yepp, after fixing NeSyPatterns/AS.der.hs (see above). However, is it possible to fix the remaining warnings, too?
[warnings.txt](https://github.com/spechub/Hets/files/9699347/warnings.txt)

**Comment by tillmo** [comment]
@daniilsvc could you please take care of the warning?
@jelmd could you please build the jammy packages anyway? (Currently, I can install neither `hets-desktop` nor `hets-server`)

**Comment by b-gehrke** [comment]
I'm looking into the warnings. I noticed the following in [Persistence/DatabaseConnection.hs:40](https://github.com/spechub/Hets/blob/master/Persistence/DatabaseConnection.hs#L40):

```hs
getConnection dbConfig = case adapter dbConfig of
#ifdef MYSQL
  Just "mysql" -> Fail.fail mySQLErrorMessage
  Just "mysql2" -> Fail.fail mySQLErrorMessage
  Just "mysql" -> return $ MySQL.connection dbConfig $
                    fromMaybe defaultPoolSize $ pool dbConfig
  Just "mysql" -> return $ MySQL.connection dbConfig $
                    fromMaybe defaultPoolSize $ pool dbConfig
#endif
...
```

With this implementation mysql support is always disabled even, if `MYSQL` flag is set. Is this the intended behaviour? I would expect to enable the support if the `MYSQL` flag is set and disable it if the flag is not set.

**Comment by b-gehrke** [comment]
So, if hets is build with the `MYSQL` flag defined, mysql support should be added. And if hets is build without the flag there should be no mysql support. Correct?

**Comment by jelmd** [comment]
Yes. If build with, make sure the related dependencies (e.g. persistent-mysql) are available, too.

**Comment by b-gehrke** [comment]
Since there is absolutely no comment on your bug report should we switch to a different tool for creating the debian packages? What about [cabal-debian](https://hackage.haskell.org/package/cabal-debian)?

**Comment by jelmd** [comment]
Have you already tried it (e.g. with `hexpat`)? It reads like that it just creates the `DEBIAN/*` files. But this is not the problem at all. The problem is just the buggy check, which causes the packaging itself to fail (as we can see, the build process works as expected w/o any errors). So perhaps adding a patch, which fixes ghc-pkg at the start of the build process is probably better than getting into a cyclic/unwanted dependency problem.
BTW: Not sure, whether ghc-pkg is a debian add-on, or whether it is provided by ghc itself ...

**Comment by jelmd** [comment]
Since patching bogus `/usr/share/haskell-devscripts/Dh_Haskell.sh` does not work on launchpad PPA and Ubuntu maintainers do not care, I replaced the `haskell-devscripts-minimal` package with our own fixed version. Should get installed automatically if one tries to build the required non-hets haskell packages - it is not required to build hets.
So closing because packages are now available on launchpad PPA for jammy, too.

**Comment by tillmo** [comment]
many thnx, good that this works now!
